package webshop;

/**
 * Created by Amir i Masha on 2016.09.22..
 */
public enum WebShopMenuEnum {
    LOGIN_USER,
    LOGOUT_USER,

    PRODUCTS_SHOW_IN_CATALOG,
    BASKET_ADD_PRODUCT,
    BASKET_REMOVE_PRODUCT,
    BASKET_BUY_PRODUCTS,

    CATALOG_ADD_PRODUCT,
    CATALOG_DISABLE_PRODUCT,
    CATALOG_ENABLE_PRODUCT,
    CATALOG_CHANGE_PRODUCT_PRICE,

    USER_LIST_USERS,
    USER_ADD_USER,
    USER_ENABLE_USER,
    USER_DISABLE_USER;

}
